development:
  password: ${PASSWORD}
  theme_id: "${DEV_THEME}"
  store: ${STORE}
  directory: dist/
  ignore:
    config/settings_data.json

production:
  password: ${PASSWORD}
  theme_id: "${PROD_THEME}"
  store: ${STORE}
  directory: dist/
  ignore:
    config/settings_data.json